cors:
  allowed-origins:
    - "https://example.com"
  allowed-origin-patterns: []
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed-headers:
    - "*"
  allow-credentials: true
